export const PROPERTIES = [
    {
        title: "Departamento en venta (Ventura, Los Laureles)",
        featuredImage: "https://homehunters.idealscloud.uk/wp-content/uploads/2023/08/DJI_20230429_44458_894-p.-m-scaled.jpg",
        codigo: "2.3MA",
        zonaDeLaPropiedad: "Asunción",
        ciudadDelDeptoCentral: "",
        ciudadDelDeptoCordillera: "",
        barrioAsuncion: "Los Laureles",
        tipoDeOperacion: "Venta",
        tipoDePropiedad: "Departamento",
        precioDeVentaUsd: 122000,
        precioDeVentaGs: 890000000,
        precioDeAlquilerUsd: null,
        precioDeAlquilerGs: null,
        m2DeConstruccion: null,
        m2DeTerreno: null,
        m2Propios: null,
    },
    {
        title: "Venta de terreno zona CIT",
        featuredImage: "https://homehunters.idealscloud.uk/wp-content/uploads/2023/08/terreno_cit-1.jpg",
        codigo: "7.1SG",
        zonaDeLaPropiedad: "Asunción",
        ciudadDelDeptoCentral: "",
        ciudadDelDeptoCordillera: "",
        barrioAsuncion: "Ytay",
        tipoDeOperacion: "Venta",
        tipoDePropiedad: "Terrenos",
        precioDeVentaUsd: 1200000,
        precioDeVentaGs: 8740000000,
        precioDeAlquilerUsd: null,
        precioDeAlquilerGs: null,
        m2DeConstruccion: null,
        m2DeTerreno: 3428,
        m2Propios: null,
    },
    {
        title: "Departamento semi-amoblado en venta (Edificio Boulevard)",
        featuredImage: "https://homehunters.idealscloud.uk/wp-content/uploads/2023/08/IMG_8132-scaled.jpg",
        codigo: "2.4MM",
        zonaDeLaPropiedad: "Asunción",
        ciudadDelDeptoCentral: "",
        ciudadDelDeptoCordillera: "",
        barrioAsuncion: "Manorá",
        tipoDeOperacion: "Venta",
        tipoDePropiedad: "Departamentos",
        precioDeVentaUsd: 290000,
        precioDeVentaGs: 2100000000,
        precioDeAlquilerUsd: null,
        precioDeAlquilerGs: null,
        m2DeConstruccion: null,
        m2DeTerreno: null,
        m2Propios: 189,
    },
    {
        title: "Departamento en venta (Habitalis Molas López)",
        featuredImage: "https://homehunters.idealscloud.uk/wp-content/uploads/2023/08/DJI_20230429_44458_894-p.-m-scaled.jpg",
        codigo: "2.2ND",
        zonaDeLaPropiedad: "Asunción",
        ciudadDelDeptoCentral: "",
        ciudadDelDeptoCordillera: "",
        barrioAsuncion: "Las Lomas (Carmelitas)",
        tipoDeOperacion: "Venta/Alquiler",
        tipoDePropiedad: "Departamentos",
        precioDeVentaUsd: 155000,
        precioDeVentaGs: 1130000000,
        precioDeAlquilerUsd: 2000,
        precioDeAlquilerGs: 14500000,
        m2DeConstruccion: null,
        m2DeTerreno: null,
        m2Propios: 88,
    },
    {
        title: "Departamentos en venta (Insignia)",
        featuredImage: "https://homehunters.idealscloud.uk/wp-content/uploads/2023/08/IMG_5626-scaled.jpg",
        codigo: "3.1SG",
        zonaDeLaPropiedad: "Central",
        ciudadDelDeptoCentral: "Luque",
        ciudadDelDeptoCordillera: "",
        barrioAsuncion: "",
        tipoDeOperacion: "Venta",
        tipoDePropiedad: "Departamentos",
        precioDeVentaUsd: 71239,
        precioDeVentaGs: 520000000,
        precioDeAlquilerUsd: null,
        precioDeAlquilerGs: null,
        m2DeConstruccion: null,
        m2DeTerreno: null,
        m2Propios: 60,
    },
    {
        title: "Departamentos en venta (Jade Park)",
        featuredImage: "https://homehunters.idealscloud.uk/wp-content/uploads/2023/08/IMG_3460-scaled.jpg",
        codigo: "2.1FD",
        zonaDeLaPropiedad: "Asunción",
        ciudadDelDeptoCentral: "",
        ciudadDelDeptoCordillera: "",
        barrioAsuncion: "Mburucuyá",
        tipoDeOperacion: "Venta",
        tipoDePropiedad: "Departamentos",
        precioDeVentaUsd: 2300000,
        precioDeVentaGs: 16700000000,
        precioDeAlquilerUsd: null,
        precioDeAlquilerGs: null,
        m2DeConstruccion: null,
        m2DeTerreno: null,
        m2Propios: 407,
    },
    {
        title: "Dúplex en venta (Pampa Grande)",
        featuredImage: "https://homehunters.idealscloud.uk/wp-content/uploads/2023/08/44572a95-4754-4ab9-8922-e65ea1ecf662.jpg",
        codigo: "5.2FD",
        zonaDeLaPropiedad: "Central",
        ciudadDelDeptoCentral: "Luque",
        ciudadDelDeptoCordillera: "",
        barrioAsuncion: "",
        tipoDeOperacion: "Venta",
        tipoDePropiedad: "Dúplex",
        precioDeVentaUsd: 180000,
        precioDeVentaGs: 1300000000,
        precioDeAlquilerUsd: null,
        precioDeAlquilerGs: null,
        m2DeConstruccion: 150,
        m2DeTerreno: 225,
        m2Propios: null,
    },
    {
        title: "Casa en venta (Casabella)",
        featuredImage: "https://homehunters.idealscloud.uk/wp-content/uploads/2023/08/DJI_20230419_40954_341-p.-m.-2-scaled.jpg",
        codigo: "5.1ND",
        zonaDeLaPropiedad: "Asunción",
        ciudadDelDeptoCentral: "",
        ciudadDelDeptoCordillera: "",
        barrioAsuncion: "Mburucuyá",
        tipoDeOperacion: "Venta/Alquiler",
        tipoDePropiedad: "Departamentos",
        precioDeVentaUsd: 495000,
        precioDeVentaGs: 3600000000,
        precioDeAlquilerUsd: 2000,
        precioDeAlquilerGs: 14500000,
        m2DeConstruccion: null,
        m2DeTerreno: null,
        m2Propios: 70,
    },
]